name: yaoyao-funcs

services:
  # Comment this if you don't want to run the API server container
  yaoyaoapi:
    build: .
    container_name: yaoyaoapi
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - yaoyaodb
      - yaoyaoredis
    networks:
      - yaoyao-network
    volumes:
      - .:/app
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod

  yaoyaodb:
    image: postgres:17
    container_name: yaoyaodb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: yaoyaodb
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/data/db
    networks:
      - yaoyao-network

  yaoyaoredis:
    image: redis:8.4-alpine
    container_name: yaoyaoredis
    restart: always
    command: ["redis-server", "--requirepass", "pass"]
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - yaoyao-network

networks:
  yaoyao-network:
    driver: bridge

volumes:
  redis-data:
  yaoyao-volume:
  go-build-cache:
  go-mod-cache:
